var JOURNAL = [
  { "events": ["zanahoria", "ejercicio", "fin de semana"], "squirrel": false },
  { "events": ["pan", "pudding", "cepillarse los dientes", "fin de semana", "touched tree"], "squirrel": false },
  { "events": ["zanahoria", "nachos", "cepillarse los dientes", "cycling", "fin de semana"], "squirrel": false },
  { "events": ["brussel sprouts", "ice cream", "cepillarse los dientes", "computer", "fin de semana"], "squirrel": false },
  { "events": ["potatoes", "candy", "cepillarse los dientes", "ejercicio", "fin de semana", "dentist"], "squirrel": false },
  { "events": ["brussel sprouts", "pudding", "cepillarse los dientes", "running", "fin de semana"], "squirrel": false },
  { "events": ["pizza", "cepillarse los dientes", "computer", "work", "touched tree"], "squirrel": false },
  { "events": ["pan", "beer", "cepillarse los dientes", "cycling", "work"], "squirrel": false },
  { "events": ["cauliflower", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["pizza", "cepillarse los dientes", "cycling", "work"], "squirrel": false },
  { "events": ["lasagna", "nachos", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["cepillarse los dientes", "fin de semana", "touched tree"], "squirrel": false },
  { "events": ["lettuce", "cepillarse los dientes", "television", "fin de semana"], "squirrel": false },
  { "events": ["spaghetti", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["cepillarse los dientes", "computer", "work"], "squirrel": false },
  { "events": ["lettuce", "nachos", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["zanahoria", "cepillarse los dientes", "running", "work"], "squirrel": false },
  { "events": ["cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["cauliflower", "reading", "fin de semana"], "squirrel": false },
  { "events": ["pan", "cepillarse los dientes", "fin de semana"], "squirrel": false },
  { "events": ["lasagna", "cepillarse los dientes", "ejercicio", "work"], "squirrel": false },
  { "events": ["spaghetti", "cepillarse los dientes", "reading", "work"], "squirrel": false },
  { "events": ["zanahoria", "ice cream", "cepillarse los dientes", "television", "work"], "squirrel": false },
  { "events": ["spaghetti", "nachos", "work"], "squirrel": false },
  { "events": ["cauliflower", "ice cream", "cepillarse los dientes", "cycling", "work"], "squirrel": false },
  { "events": ["spaghetti", "cacahuetes", "computer", "fin de semana"], "squirrel": true },
  { "events": ["potatoes", "ice cream", "cepillarse los dientes", "computer", "fin de semana"], "squirrel": false },
  { "events": ["potatoes", "ice cream", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["cacahuetes", "cepillarse los dientes", "running", "work"], "squirrel": false },
  { "events": ["potatoes", "ejercicio", "work"], "squirrel": false },
  { "events": ["pizza", "ice cream", "computer", "work"], "squirrel": false },
  { "events": ["lasagna", "ice cream", "work"], "squirrel": false },
  { "events": ["cauliflower", "candy", "reading", "fin de semana"], "squirrel": false },
  { "events": ["lasagna", "nachos", "cepillarse los dientes", "running", "fin de semana"], "squirrel": false },
  { "events": ["potatoes", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["zanahoria", "work"], "squirrel": false },
  { "events": ["pizza", "beer", "work", "dentist"], "squirrel": false },
  { "events": ["lasagna", "pudding", "cycling", "work"], "squirrel": false },
  { "events": ["spaghetti", "cepillarse los dientes", "reading", "work"], "squirrel": false },
  { "events": ["spaghetti", "pudding", "television", "fin de semana"], "squirrel": false },
  { "events": ["pan", "cepillarse los dientes", "ejercicio", "fin de semana"], "squirrel": false },
  { "events": ["lasagna", "cacahuetes", "work"], "squirrel": true },
  { "events": ["pizza", "work"], "squirrel": false },
  { "events": ["potatoes", "ejercicio", "work"], "squirrel": false },
  { "events": ["cepillarse los dientes", "ejercicio", "work"], "squirrel": false },
  { "events": ["spaghetti", "cepillarse los dientes", "television", "work"], "squirrel": false },
  { "events": ["pizza", "cycling", "fin de semana"], "squirrel": false },
  { "events": ["zanahoria", "cepillarse los dientes", "fin de semana"], "squirrel": false },
  { "events": ["zanahoria", "beer", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["pizza", "cacahuetes", "candy", "work"], "squirrel": true },
  { "events": ["zanahoria", "cacahuetes", "cepillarse los dientes", "reading", "work"], "squirrel": false },
  { "events": ["potatoes", "cacahuetes", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["zanahoria", "nachos", "cepillarse los dientes", "ejercicio", "work"], "squirrel": false },
  { "events": ["pizza", "cacahuetes", "cepillarse los dientes", "television", "fin de semana"], "squirrel": false },
  { "events": ["lasagna", "cepillarse los dientes", "cycling", "fin de semana"], "squirrel": false },
  { "events": ["cauliflower", "cacahuetes", "cepillarse los dientes", "computer", "work", "touched tree"], "squirrel": false },
  { "events": ["lettuce", "cepillarse los dientes", "television", "work"], "squirrel": false },
  { "events": ["potatoes", "cepillarse los dientes", "computer", "work"], "squirrel": false },
  { "events": ["pan", "candy", "work"], "squirrel": false },
  { "events": ["potatoes", "nachos", "work"], "squirrel": false },
  { "events": ["zanahoria", "pudding", "cepillarse los dientes", "fin de semana"], "squirrel": false },
  { "events": ["zanahoria", "cepillarse los dientes", "ejercicio", "fin de semana", "touched tree"], "squirrel": false },
  { "events": ["brussel sprouts", "running", "work"], "squirrel": false },
  { "events": ["cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["lettuce", "cepillarse los dientes", "running", "work"], "squirrel": false },
  { "events": ["candy", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["brussel sprouts", "cepillarse los dientes", "computer", "work"], "squirrel": false },
  { "events": ["pan", "cepillarse los dientes", "fin de semana"], "squirrel": false },
  { "events": ["cauliflower", "cepillarse los dientes", "fin de semana"], "squirrel": false },
  { "events": ["spaghetti", "candy", "television", "work", "touched tree"], "squirrel": false },
  { "events": ["zanahoria", "pudding", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["lettuce", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["zanahoria", "ice cream", "cepillarse los dientes", "cycling", "work"], "squirrel": false },
  { "events": ["pizza", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["spaghetti", "cacahuetes", "ejercicio", "fin de semana"], "squirrel": true },
  { "events": ["pan", "beer", "computer", "fin de semana", "touched tree"], "squirrel": false },
  { "events": ["cepillarse los dientes", "running", "work"], "squirrel": false },
  { "events": ["lettuce", "cacahuetes", "cepillarse los dientes", "work", "touched tree"], "squirrel": false },
  { "events": ["lasagna", "cepillarse los dientes", "television", "work"], "squirrel": false },
  { "events": ["cauliflower", "cepillarse los dientes", "running", "work"], "squirrel": false },
  { "events": ["zanahoria", "cepillarse los dientes", "running", "work"], "squirrel": false },
  { "events": ["zanahoria", "reading", "fin de semana"], "squirrel": false },
  { "events": ["zanahoria", "cacahuetes", "reading", "fin de semana"], "squirrel": true },
  { "events": ["potatoes", "cepillarse los dientes", "running", "work"], "squirrel": false },
  { "events": ["lasagna", "ice cream", "work", "touched tree"], "squirrel": false },
  { "events": ["cauliflower", "cacahuetes", "cepillarse los dientes", "cycling", "work"], "squirrel": false },
  { "events": ["pizza", "cepillarse los dientes", "running", "work"], "squirrel": false },
  { "events": ["lettuce", "cepillarse los dientes", "work"], "squirrel": false },
  { "events": ["pan", "cepillarse los dientes", "television", "fin de semana"], "squirrel": false },
  { "events": ["cauliflower", "cacahuetes", "cepillarse los dientes", "fin de semana"], "squirrel": false }
];

// This makes sure the data is exported in node.js —
// `require('./path/to/journal.js')` will get you the array.
if (typeof module != "undefined" && module.exports && (typeof window == "undefined" || window.exports != exports))
  module.exports = JOURNAL;
if (typeof global != "undefined" && !global.JOURNAL)
  global.JOURNAL = JOURNAL;
